language: go

go:
  - 1.7

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - git clone https://github.com/ntsvetko/gobucks.git
  - go get -u github.com/tools/godep
  - godep restore

script:
  - go test -v ./...